// ===== 公众号内容来源卡 Mock 数据 =====
import { OASourceCard } from '@/lib/oa/types';

export const OA_SOURCE_CARDS: OASourceCard[] = [
  // ===== 热转印方向 =====
  {
    id: 'ht_01', type: 'knowledge', businessLine: 'heat_transfer',
    title: '热转印膜好不好怎么看',
    targetAudience: '正在接触热转印的采购或工艺人员',
    customerPain: '不知道用什么标准判断花膜好坏',
    coreConclusion: '热转印膜好不好，不能只看价格，要看离型效果、油墨遮盖力、胶水匹配性和批次稳定性。',
    keyPoints: [
      '离型层：转印时是否顺畅剥离，不残留',
      '油墨层：遮盖力够不够，颜色是否饱和',
      '胶水层：跟材质是否匹配，附着力达不达标',
      '批次稳定性：每次做货颜色和性能是否一致',
    ],
    applicableScenarios: ['采购花膜时做供应商评估', '首次合作寄样测试'],
    unsuitableScenarios: ['已有长期稳定供应商的批量采购'],
    riskNotes: ['不要仅凭一张样品判断整批质量'],
    suggestedCTA: '寄样测试，我帮你评估花膜质量',
    outboundAllowed: true, updatedAt: '2026-07-01',
  },
  {
    id: 'ht_02', type: 'knowledge', businessLine: 'digital_heat_transfer',
    title: '数码热转印为什么不用起版',
    targetAudience: '小批量多图案需求的品牌方或加工厂',
    customerPain: '传统凹印起版费高，小批量不划算',
    coreConclusion: '数码热转印不需要制版，电脑出图直接打印，一张起印，单件成本与批量无关。',
    keyPoints: [
      '凹印制版费通常几千元起，数码热转印零制版',
      '一件也能做，设计稿确认后当天出样',
      '颜色还原度高，渐变色和精细图案都能做',
      '缺点是批量单价高于凹印，量大还是凹印划算',
    ],
    applicableScenarios: ['小批量多图案（50-2000件）', '打样验证阶段'],
    unsuitableScenarios: ['大批量单色图案（建议凹印）'],
    riskNotes: ['数码大货颜色与打样存在细微差异属正常现象'],
    suggestedCTA: '发图评估，我帮你判断适合数码还是凹印',
    outboundAllowed: true, updatedAt: '2026-07-02',
  },
  {
    id: 'ht_03', type: 'faq', businessLine: 'heat_transfer',
    title: '热转印打样前要确认哪些信息',
    targetAudience: '准备打样的客户或采购',
    customerPain: '打样来回次数多，效率低',
    coreConclusion: '打样前确认材质、尺寸、颜色标准、测试要求和数量，一次打样成功率提升80%。',
    keyPoints: [
      '材质：PE、PP、ABS、玻璃、金属——不同材质工艺完全不同',
      '尺寸：产品直径、高度、弧度影响花膜排版',
      '颜色标准：潘通号或实物样，手机图片有色差',
      '测试要求：耐酒精、耐磨、耐刮、洗碗机测试',
      '数量：小批量和大批量的工艺路径可能不同',
    ],
    applicableScenarios: ['首次打样', '变更材质或工艺时'],
    riskNotes: ['打样确认后需保留封样，大货时对照'],
    suggestedCTA: '发产品图和材质，我帮你准备打样清单',
    outboundAllowed: true, updatedAt: '2026-07-03',
  },
  {
    id: 'ht_04', type: 'knowledge', businessLine: 'heat_transfer',
    title: 'PE/PP材料为什么要先测试',
    targetAudience: '使用PE或PP材质的日化/化妆品品牌方',
    customerPain: 'PE/PP印上去容易掉，不知道问题出在哪',
    coreConclusion: 'PE和PP表面能低，属于难粘材料，必须测试表面处理状态和附着力，不能直接承诺。',
    keyPoints: [
      'PE/PP表面能低于38mN/m，普通胶水附着力不够',
      '部分PE瓶经过电晕或火焰处理，附着力达标',
      '未处理的PE/PP必须先做表面处理才能印刷',
      '不做测试直接大货，脱落风险很高',
    ],
    applicableScenarios: ['PE瓶热转印', 'PP杯印刷', '日化品包装'],
    unsuitableScenarios: ['确认已做表面处理的材料'],
    riskNotes: ['即使处理过，不同批次也可能有差异', '不要承诺"保证不掉"'],
    suggestedCTA: '寄样免费测附着力，做不了会直接告诉你',
    outboundAllowed: true, updatedAt: '2026-07-04',
  },
  {
    id: 'ht_05', type: 'case', businessLine: 'heat_transfer',
    title: '热转印偏位常见原因',
    targetAudience: '正在用热转印但出现偏位的客户',
    customerPain: '转印位置偏，废品率高',
    coreConclusion: '热转印偏位通常不是机器问题，是治具设计、产品公差或定位方案的问题。',
    keyPoints: [
      '治具与产品配合间隙过大，转印时移位',
      '产品本身公差大，前一后一个位置差0.5mm',
      '定位方式：机械定位 vs 视觉定位，精度差异大',
      '花膜张力不均匀也会导致图案偏位',
    ],
    applicableScenarios: ['热转印生产中出现偏位', '新项目设计治具时'],
    riskNotes: ['偏位问题一般通过调整治具和定位方案解决'],
    suggestedCTA: '发产品图，我帮你诊断偏位原因',
    outboundAllowed: true, updatedAt: '2026-07-05',
  },
  {
    id: 'ht_06', type: 'faq', businessLine: 'heat_transfer',
    title: '常规热转印和数码热转印怎么选',
    targetAudience: '需确定转印工艺的品牌方或贸易商',
    customerPain: '不确定选常规还是数码热转印',
    coreConclusion: '量大的单色/少色常规凹印更划算；小批量多图案数码更灵活；有打样需求先用数码确认。',
    keyPoints: [
      '常规凹印：起版费3000-8000元，量大单价低',
      '数码热转印：零起版费，但单价高于凹印',
      '混色和渐变色：数码优势明显',
      '组合方案：数码打样 → 确认后转凹印量产',
    ],
    applicableScenarios: ['新项目工艺选型', '批量与成本评估'],
    unsuitableScenarios: ['单色超大订单（建议直接凹印）'],
    riskNotes: ['数码和凹印的颜色呈现有差异，需分别确认色样'],
    suggestedCTA: '发数量和图案，我帮你算两种方案的成本对比',
    outboundAllowed: true, updatedAt: '2026-07-06',
  },
  // ===== UV机器方向 =====
  {
    id: 'uv_01', type: 'equipment', businessLine: 'uv_machine',
    title: '买UV机器前要看哪些项',
    targetAudience: '计划采购UV打印机的工厂老板',
    customerPain: '市场上UV机器品牌多，不知道怎么选',
    coreConclusion: '买UV打印机前，确认四个核心项：打印宽幅、墨水类型、色彩配置和售后服务。',
    keyPoints: [
      '宽幅：根据最大产品尺寸选择，不要买小了',
      '墨水：UV墨水、弱溶剂、环保墨水——适用场景不同',
      '色彩配置：CMYK + 白墨是最低配置',
      '售后：机器故障响应时间、配件供应、培训支持',
    ],
    applicableScenarios: ['首次采购UV打印机', '设备升级更换'],
    unsuitableScenarios: ['已有成熟供应商且满意的情况'],
    riskNotes: ['不要只看参数，必须看实际打印样品'],
    suggestedCTA: '发产品应用场景，我帮你推荐合适机型',
    outboundAllowed: true, updatedAt: '2026-07-07',
  },
  {
    id: 'uv_02', type: 'equipment', businessLine: 'uv_machine',
    title: 'UV机器不是只看参数',
    targetAudience: '准备采购UV设备的客户',
    customerPain: '比了一圈参数，但实际效果和售后跟不上',
    coreConclusion: 'UV机器最终效果取决于墨水、喷头、icc曲线和操作人员的配合，只看参数容易踩坑。',
    keyPoints: [
      '同参数不同品牌，实际打印效果差距很大',
      'ICC色彩曲线决定了颜色还原度',
      '喷头保养和操作培训直接影响设备寿命',
      '售后响应时间比机器贵不贵更重要',
    ],
    applicableScenarios: ['对比UV设备供应商时'],
    riskNotes: ['要求供应商提供同类型产品的实际打印样品'],
    suggestedCTA: '预约到厂看实际打印效果，眼见为实',
    outboundAllowed: true, updatedAt: '2026-07-08',
  },
  {
    id: 'uv_03', type: 'knowledge', businessLine: 'uv_machine',
    title: 'UV设备交付为什么要包含培训和调试',
    targetAudience: '购买UV设备的工厂',
    customerPain: '设备买回来但用不好，故障率高',
    coreConclusion: 'UV打印机的效果70%取决于操作人员的调试水平，培训与调试是交付不可或缺的环节。',
    keyPoints: [
      '设备的ICC曲线需要根据实际使用环境调整',
      '操作培训直接影响生产效率和废品率',
      '定期保养能延长喷头寿命数倍',
      '完整体验包括：安装调试 + 操作培训 + 打样辅导',
    ],
    applicableScenarios: ['新设备验收', '操作人员更换时'],
    riskNotes: ['要求供应商提供完整的培训计划和售后通道'],
    suggestedCTA: '咨询宏达UV设备的交付流程和培训体系',
    outboundAllowed: true, updatedAt: '2026-07-09',
  },
  {
    id: 'uv_04', type: 'faq', businessLine: 'uv_machine',
    title: 'UV机器适合哪些制造业客户',
    targetAudience: '不同行业的潜在客户',
    customerPain: '不确定UV打印是否适合自己的产品',
    coreConclusion: 'UV打印适合小批量定制、多品种切换快、精度要求高的场景，不适合单一产品大批量印刷。',
    keyPoints: [
      '适合：电子产品外壳、礼品定制、标牌铭牌、工艺品',
      '不适合：单色大批量印刷（建议丝印或移印）',
      '优势：无需制版，换图即打，灵活度高',
      '注意：UV油墨附着力需根据材质选择',
    ],
    applicableScenarios: ['新项目评估是否适合UV打印'],
    unsuitableScenarios: ['大批量单色印刷'],
    riskNotes: ['不同材质需测试附着力，不能一概而论'],
    suggestedCTA: '发产品图片，我帮你判断是否适合UV打印',
    outboundAllowed: true, updatedAt: '2026-07-10',
  },
  // ===== 品牌方向 =====
  {
    id: 'brand_01', type: 'brand', businessLine: 'brand',
    title: '宏达40多年表面印刷经验如何沉淀',
    targetAudience: '关注供应商背景和实力的客户',
    customerPain: '担心供应商经验和稳定性',
    coreConclusion: '宏达印业40多年来把经验沉淀为标准化工艺数据库、案例库和培训体系，不是靠个人经验。',
    keyPoints: [
      '累计数万个产品案例，覆盖各类材质和工艺',
      '每个项目都有标准工艺单和测试报告',
      '新工艺开发有完整试产流程',
    ],
    applicableScenarios: ['客户考察供应商时', '品牌宣传场景'],
    riskNotes: ['宣传时引用具体数据需确保准确'],
    suggestedCTA: '到厂参观，看我们的工艺数据库和案例',
    outboundAllowed: true, updatedAt: '2026-07-11',
  },
  {
    id: 'brand_02', type: 'brand', businessLine: 'brand',
    title: '宏达不只是花膜和加工，也在做设备与解决方案',
    targetAudience: '需要整体解决方案的品牌方',
    customerPain: '以为宏达只做花膜，不知道宏达也做设备和整体方案',
    coreConclusion: '宏达已从单一花膜加工升级为设备+材料+工艺的一体化解决方案供应商。',
    keyPoints: [
      '自有花膜生产线，保证供应和质量',
      'UV打印设备研发和生产能力',
      '工艺开发+打样+量产+设备一体化',
    ],
    applicableScenarios: ['需要全流程支持的品牌方'],
    riskNotes: ['整体方案需根据客户实际情况定制'],
    suggestedCTA: '联系销售，了解宏达整体解决方案',
    outboundAllowed: true, updatedAt: '2026-07-12',
  },
];

export function getOASourceCardsByIds(ids: string[]): OASourceCard[] {
  return OA_SOURCE_CARDS.filter(c => ids.includes(c.id));
}

export function getOASourceCardsByBusinessLine(line: string): OASourceCard[] {
  return OA_SOURCE_CARDS.filter(c => c.businessLine === line);
}

export function getOASourceCardsByType(type: string): OASourceCard[] {
  return OA_SOURCE_CARDS.filter(c => c.type === type);
}
