-- Upgrade topics table with planning fields
ALTER TABLE topics ADD COLUMN IF NOT EXISTS platform text DEFAULT '';
ALTER TABLE topics ADD COLUMN IF NOT EXISTS topic_source text DEFAULT '';
ALTER TABLE topics ADD COLUMN IF NOT EXISTS target_customer text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS customer_pain text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS product_process text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS material text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS content_angle text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS core_point text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS why_user_watch text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS content_purpose text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS conversion_goal text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS comment_guidance text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS private_message_action text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS risk_rules text[];
ALTER TABLE topics ADD COLUMN IF NOT EXISTS script_status text DEFAULT '未生成';
ALTER TABLE topics ADD COLUMN IF NOT EXISTS linked_script_id uuid;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS linked_post_id uuid;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS owner_id uuid;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS last_action text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS is_this_week boolean DEFAULT false;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS planned_shoot_date date;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS planned_publish_date date;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS shooting_method text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS video_length text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS required_products text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS required_shots text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS required_factory_assets text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS logo_risk text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS privacy_risk text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS knowledge_refs text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS faq_refs text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS case_refs text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS viral_refs text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS review_refs text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS topic_score int;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS score_detail jsonb;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS risk_level text;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS risk_result text;

COMMENT ON COLUMN topics.platform IS '目标平台：视频号/抖音/两者都适合';
COMMENT ON COLUMN topics.topic_source IS '选题来源：客户私信/评论区/销售反馈/爆款拆解等';
COMMENT ON COLUMN topics.target_customer IS '目标客户画像';
COMMENT ON COLUMN topics.customer_pain IS '客户痛点/问题';
COMMENT ON COLUMN topics.product_process IS '关联产品/工艺';
COMMENT ON COLUMN topics.material IS '关联材料';
COMMENT ON COLUMN topics.content_angle IS '内容切入角度';
COMMENT ON COLUMN topics.core_point IS '核心观点';
COMMENT ON COLUMN topics.why_user_watch IS '用户为什么愿意看';
COMMENT ON COLUMN topics.content_purpose IS '内容目的';
COMMENT ON COLUMN topics.conversion_goal IS '转化目标';
COMMENT ON COLUMN topics.comment_guidance IS '评论区引导话术';
COMMENT ON COLUMN topics.private_message_action IS '私信承接动作';
COMMENT ON COLUMN topics.script_status IS '脚本状态：未生成/已生成/待审核/已审核/已退回/已关联发布';
COMMENT ON COLUMN topics.linked_script_id IS '关联脚本ID';
COMMENT ON COLUMN topics.linked_post_id IS '关联发布视频ID';
COMMENT ON COLUMN topics.owner_id IS '选题负责人';
COMMENT ON COLUMN topics.last_action IS '最后操作记录';
COMMENT ON COLUMN topics.is_this_week IS '是否本周选题';
COMMENT ON COLUMN topics.planned_shoot_date IS '计划拍摄日期';
COMMENT ON COLUMN topics.planned_publish_date IS '计划发布日期';
